### ISSUE TITLE
The following program is not handled correctly

### ISSUE THREAD

**Issue by dcu** [timakin/bodyclose#6]
```go
package main

import (
	"io"
	"net/http"
)

func closeBody(c io.Closer) {
	_ = c.Close()
}

func main() {
	resp, _ := http.Get("https://example.com")
	defer closeBody(resp.Body)
}
```

**Comment by dcu** [comment]
another one:

```go
package main

import (
	"net/http"
)

func main() {
	resp, _ := http.Get("https://example.com")
	defer func() {
		_ = resp.Body.Close()
	}()
}
```

**Comment by djui** [comment]
And another one:

```go
resp, err := c.do(req)
if err != nil {
	return nil, err
}
defer func() { log.HandleError(resp.Body.Close()) }()
```

**Comment by timakin** [comment]
Thank you for your reports and I'm sorry for being late to supoort.
I'll fix them all.

**Comment by dcu** [comment]
thanks, and thanks for working on this I think it's really really really needed and will solve a very common issue, even in production

**Comment by timakin** [comment]
@dcu 
Now I fixed all of them. And test cases below passed!
https://github.com/timakin/bodyclose/blob/master/passes/bodyclose/testdata/src/a/issue3.go

**Comment by djui** [comment]
I can't fully confirm that the fix addresses all items. I still see about 80% of false negatives on a repo of mine. One example:

```go
resp, err := t.C.Do(req)
require.NoError(t, err)

defer func() { require.NoError(t, resp.Body.Close()) }()
```

It's the same pattern of my previous example, just a different wrapper function.

**Comment by dcu** [comment]
I created new issues for cases I found
